name: Continuous Integration

on: [pull_request]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Jest unit coverage comment
        uses: ArtiomTr/jest-coverage-report-action@v2        
        with:
          test-script: npm run test-coverage